<div class="active_page">
    <div data-mage-init='{"banner":{}}'  class="high-banner">
        <div class="left-banner">
            <p class="left-banner-center"><?= __("Existing customers sign in or register for member discounts")?></p>
        </div>
        <div class="right-banner">
            <p class="right-banner-center"><?= __("Discover more about ActiveLife")?></p>
        </div>
    </div>
    <div class="content-active">
        <img class="content-active-img" src="<?php echo $block->getViewFileUrl('./images/desktop.jpg'); ?>"/>
        <div class="middle">
            <h1 class="middle-title"><?= __("ActiveLife")?></h1>
            <div class="middle-line"></div>
            <p class="middle-text"><?= __("Good health through smarter products")?></p>
        </div>
        <div class="low">
            <div class="low-item">
                <span class="low-item-title"><?= __("SHONA VERTUE")?></span>
                <p class="low-item-text"><?= __("Read the PT's tips to improve your wellbeing")?></p>
            </div>
            <div class="low-item">
                <span class="low-item-title"><?= __("REALISE HEALTH")?></span>
                <p class="low-item-text"><?= __("Understand your body with our range og at-home health assessments")?></p>
            </div>
            <div class="low-item">
                <span class="low-item-title"><?= __("PUREGYM")?></span>
                <p class="low-item-text"><?= __("Smash your fitness goals in the UK's largest gym chain")?></p>
            </div>
        </div>
    </div>
</div>
